config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  resources :users, only:[:index, :show]
  resources :friend_requests, only:[:index, :create, :update, :destroy]

  resources :posts, only: [:index, :show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end

  resources :comments, only: :destroy

  get "about", controller: "static_pages"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: "User"

  default_scope -> { order(created_at: :asc) }

  validates :text, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        post = Post.find_by(id: params[:post_id])
        comment = post.comments.build(text: params[:text], author: current_user)

        if comment.save
            redirect_to(request.referer || root_url)
        else
            redirect_to post_url(post)
        end
    end

    def destroy
        comment = Comment.find(params[:id])

        if comment.author_id == current_user.id
            comment.destroy
        end
        redirect_to request.referer || root_url
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment group border-b first:border-t p-2 ml-6">
    <%= link_to comment.author.name, user_path(comment.author), class: "text-blue-800 hover:text-blue-700" %>
    <%= time_tag comment.created_at, class: "text-gray-700 text-sm ml-4" %>
    <% if comment.author == current_user %>
        <%= link_to "delete", comment_path(comment),
                                method: :delete,
                                data: { confirm: "You sure?" },
                                class: "ml-4 text-sm text-blue-800 hover:text-red-700 invisible group-hover:visible" %>
    <% end %>
    <p><%= comment.text%></p>
</div>