config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  resources :users, only:[:index, :show]
  resources :friend_requests, only:[:index, :create, :update, :destroy]

  resources :posts, only: [:index, :show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end

  resources :comments, only: :destroy

  get "about", controller: "static_pages"
end

app/views/shared/_accept_request_button.html.erb
<%= form_for request, html: {class: "inline-block"} do %>
    <%= hidden_field_tag :accepted, true %>
    <%= submit_tag "Accept Friend Request", class: "social-btn" %>
<% end %>
<%= link_to "Delete Request", friend_request_path(request), method: :delete,
                                    data: { confirm: "You sure?" }, class: "social-btn social-neg ml-1" %>

app/views/shared/_post_display.html.erb
<div class="post-display m-2 mt-4 p-2 bg-white rounded shadow-md">
    <div class="byline text-md">
        <span class="text-blue-800"><%= link_to post.author.name, user_path(post.author), class: "hover:text-blue-700" %></span>
        <span class="date-time text-gray-800">
             at
            <%= link_to post_path(post), class: "hover:underline" do %>
            <%= time_tag(post.created_at) %>
            <% end %>
        </span>
    </div>
    <div class="post-content text-lg my-4">
        <p><%= post.text %></p>
    </div>
    <div class="flex">
        <span class="flex-grow text-center font-bold text-gray-700"><%= pluralize(post.like_count, 'like') %></span>
        <span class="flex-grow text-center font-bold text-gray-700"><%= pluralize(post.comments.size, 'comment') %></span>
    </div>
    <div class="post-buttons my-2 text-md">
        <% unless post.user_likes > 0 %>
        <%= form_for :like, url: post_likes_path(post.id), class: "inline-block" do |f| %>
            <%= f.submit "Like", class: "py-1 px-2 border-2 border-blue-700 rounded bg-blue-500 text-white hover:bg-blue-300 hover:text-blue-700" %>
        <% end %>
        <% else %>
            <%= link_to "Liked", post_like_path(post, 0), method: :delete,
                        class: "inline-block py-1 px-2 border-2 border-gray-300 rounded bg-white text-blue-700 hover:bg-gray-200 hover:border-gray-500 hover:text-blue-500" %>
        <% end %>
    </div>
    <div>
        <%= render post.comments %>
    </div>
    <%= form_with url: post_comments_path(post) do |f| %>
        <%= f.text_area :text, rows: 1, resizable: false, class: "resize-none w-full mt-2 mb-1 border-2 rounded px-2 py-1 focus:border-blue-300 focus:outline-none" %>
        <%= f.submit 'Comment', class: "form-btn" %>
    <% end %>
</div>

app/views/shared/_post_form.html.erb
<h2 class="text-xl mx-2 my-2">Write something</h2>
<div class="m-2">
  <%= form_for :post, url: posts_url do |f| %>
    <%= f.text_area :text, class: "w-full p-2 resize-none border-2 rounded border-blue-700 shadow-md", placeholder: "What's on your mind?" %>
    <div class="text-right my-2">
      <%= f.submit "Post", class: "form-btn px-4 shadow-md" %>
    </div>
  <% end %>
</div>

app/views/shared/_revoke_request_button.html.erb
<%= link_to "Revoke Request", friend_request_path(request), method: :delete,
                                      data: { confirm: "You sure?" }, class: "social-btn social-neg" %>

app/views/shared/_send_request_button.html.erb
<%= form_with url: friend_requests_path do %>
    <%= hidden_field_tag :friend_id, user.id %>
    <%= submit_tag "Send Friend Request", class: "social-btn" %>
<% end %>

app/views/shared/_user_list_item.html.erb
<li class="flex justify-between items-center mb-2">
  <%= link_to user.name, user_path(user), class: "text-blue-700 hover:text-blue-800" %>
  <% case type %>
  <% when :send %>
    <%= render 'shared/send_request_button', user: user %>
  <% when :accept %>
    <div class="justify-self-end">
    <%= render 'shared/accept_request_button', request: request %>
    </div>
  <% when :revoke %>
    <%= render 'shared/revoke_request_button', request: request %>
  <% end %>
</li>