config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  resources :users, only:[:index, :show]
  resources :friend_requests, only:[:index, :create, :update, :destroy]

  resources :posts, only: [:index, :show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end

  resources :comments, only: :destroy

  get "about", controller: "static_pages"
end

app/views/layouts/_footer.html.erb
<footer class="absolute inset-x-0 bottom-0 mx-2 py-1 border-t text-sm text-gray-700">
  <span class="px-4 text-blue-700 font-bold">Phacepook</span>
  <nav class="inline">
    <ul class="inline-flex">
      <li class="px-2 border-r"><%= link_to "About", about_path, class: "hover:text-gray-600" %></li>
      <%# <li class="px-2">Privacy Policy</li> %>
    </ul>
  </nav>
</footer>

app/views/layouts/_navbar.html.erb
<div class="bg-blue-700 mx-1 p-2 rounded-lg text-white md:flex md:items-center md:justify-between">
  <h1 class="text-center p-1">
    <%= link_to "Phacepook", root_path, class: "font-bold" %>
  </h1>
  <%  if current_user %>
  <div class="flex flex-wrap items-center">
    <%= link_to "Find Friends", users_path, class: "mx-1 p-1 rounded hover:bg-blue-800" %>
    <%= link_to "#{current_user.friend_offers.pending.load.size} Friend " + "Request".pluralize(current_user.friend_offers.pending.size),
                friend_requests_path, class: "mx-1 p-1 rounded hover:bg-blue-800" %>
    <div class="mx-1 px-1">
      <%= link_to user_path(current_user), class: "inline-block p-1 rounded hover:bg-blue-800" do %>
        <%= image_tag gravatar_for(current_user, size: 30), class: "inline rounded-full" %>
        <%= current_user.name %>
      <% end %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "p-1 rounded hover:bg-blue-800" %>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phacepook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="min-h-screen relative bg-gray-100 pb-8 pt-1">
    <%= render 'layouts/navbar' %>

    <% flash.each do |type, message| %>
      <% type_styles = {"alert"  => "bg-red-600",
                        "notice" => "bg-green-500",
                        "flash"  => "bg-gray-600"} %>
      <%= content_tag :div, message, class: "m-2 p-2 text-white rounded #{type_styles[type]}" %>
    <% end %>

    <div class="container mx-auto">
    <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>